import SnackbarProvider from "@/components/providers/snack-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RouteGuard from "@/components/providers/route-guard";
import QueryProvider from "@/components/providers/react-query";
import NavBar from "@/components/molecules/navbar";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SnackbarProvider>
            <RouteGuard>
              <NavBar/>
                <Box className="py-16">
                  {children}
                </Box>
            </RouteGuard>
          </SnackbarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
